Controllers/DialogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Dialog.Controllers
{
    public class DialogController : Controller
    {
        // GET: Dialog
        public ActionResult Index()
        {
            return View();
        }
        //
        public ActionResult DialogPartial() {
            return PartialView();
        }
    }
}

Views/Dialog/DialogPartial.cshtml
<div ng-controller="dialogCtrl">
    <div>
        <div>
            <label>Personens namn: </label>  <input type="text" name="personnamn" ng-model="vm.person.name" />
        </div>
        <div>
            <label>Favoritlag</label> <select ng-model="vm.person.favoriteTeam" ng-options="fv for fv in vm.favoriteTeams"></select>
        </div>
        
        <div><button ng-click="vm.loggaPerson()">Logga person</button></div>
    </div>
</div>

Views/Dialog/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Dialog</h2>

<div id="dialogWrapper" ng-controller="mainCtrl">
    <div>Angular check: {{1+1}}</div>
    <div>MainCtrl: {{vm.controllerType}}</div>
    <div ng-controller="dialogCtrl">
        <div>DialogCtrl: {{vm.controllerType}}</div>
        <div>TemplateUrl: {{vm.templateUrl}}</div>
        <button ng-click="vm.skapaDialog()">Skapa dialog</button>
        @*<button data-dialog-knapp="" ng-click="vm.skapaDialog()">Skapa dialog</button>*@
    </div>
</div>


@section scripts {

    <script src="~/Scripts/jquery-ui-1.10.4.js"></script>
    <script src="~/Scripts/angular.js"></script>
    <script src="~/Scripts/Dialog/utils.js"></script>
    <script src="~/Scripts/Dialog/dialog.js"></script>
    <script src="~/Scripts/Dialog/dialogController.js"></script>
    <script src="~/Scripts/Dialog/dialogDirective.js"></script>
    <script src="~/Scripts/Dialog/app.js"></script>
    <script>
        $(function () {
            console.log('laddar');
            var appen = new TheDialog.DialogApp('@Url.Action("DialogPartial","Dialog")');
            appen.bootstrap();
        });
    </script>

}